meta:
  id: "default_rus"
  name: "Стандартная тема (RU)"
  author: "System"
  version: "1.0"
  locale: "ru"

# Role name overrides for UI
roles:
  mafia: 
    display_name: "Мафия"
  doctor:
    display_name: "Доктор"
  prostitute:
    display_name: "Проститутка"
  commissar:
    display_name: "Комиссар"
  maniac:
    display_name: "Маньяк"
  sergeant:
    display_name: "Сержант"
  lawyer:
    display_name: "Адвокат"
  poisoner:
    display_name: "Отравитель"
  civilian:
    display_name: "Мирный житель"

# Audio events (List of variants for randomization)
audio:
  events:
    role_name_mafia:
      - file: "role_mafia.mp3"
        text: "Мафия"
    role_name_doctor:
      - file: "role_doctor.mp3"
        text: "Доктор"
    role_name_prostitute:
      - file: "role_prostitute.mp3"
        text: "Проститутка"
    role_name_commissar:
      - file: "role_commissar.mp3"
        text: "Комиссар"
    role_name_maniac:
      - file: "role_maniac.mp3"
        text: "Маньяк"
    role_name_sergeant:
      - file: "role_sergeant.mp3"
        text: "Сержант"
    role_name_lawyer:
      - file: "role_lawyer.mp3"
        text: "Адвокат"
    role_name_poisoner:
      - file: "role_poisoner.mp3"
        text: "Отравитель"
    role_name_civilian:
      - file: "role_civilian.mp3"
        text: "Мирный житель"
    game_start:
      - file: "game_start.mp3"
        text: "Игра начинается. Всем удачи."
    
    role_reveal:
      - file: "role_reveal.mp3"
        text: "Роли распределены. Посмотрите на свои устройства."
    
    night_start:
      - file: "night_start.mp3"
        text: "Наступает ночь. Город засыпает."
    
    mafia_wake:
      - file: "mafia_wake.mp3"
        text: "Мафия, просыпайтесь."
    
    mafia_lawyer_wake:
      - file: "mafia_lawyer_wake.mp3"
        text: "Мафия и Адвокат, просыпайтесь."
    
    mafia_meet:
      - file: "mafia_meet.mp3"
        text: "Мафия, просыпайтесь. Я вас вижу. Знакомьтесь."
        
    mafia_lawyer_meet:
      - file: "mafia_lawyer_meet.mp3"
        text: "Мафия и Адвокат, просыпайтесь. Я вас вижу. Знакомьтесь."
    
    prostitute_wake:
      - file: "prostitute_wake.mp3"
        text: "Проститутка, просыпайся."
        
    maniac_wake:
      - file: "maniac_wake.mp3"
        text: "Маньяк, просыпайся. Выбери свою жертву."
    
    doctor_wake:
      - file: "doctor_wake.mp3"
        text: "Доктор, просыпайся."

    commissar_wake:
      - file: "commissar_wake.mp3"
        text: "Комиссар, просыпайся."
        
    commissar_sergeant_wake:
      - file: "commissar_sergeant_wake.mp3"
        text: "Полиция, просыпайтесь. Комиссар и Сержант, я жду вас."
        
    sergeant_wake:
      - file: "sergeant_wake.mp3"
        text: "Сержант, просыпайся."
    
    lawyer_wake:
      - file: "lawyer_wake.mp3"
        text: "Адвокат, просыпайся."
        
    poisoner_wake:
      - file: "poisoner_wake.mp3"
        text: "Отравитель, просыпайся."
    
    mafia_sleep:
      - file: "mafia_sleep.mp3"
        text: "Мафия, засыпайте."
        
    mafia_lawyer_sleep:
      - file: "mafia_lawyer_sleep.mp3"
        text: "Мафия и Адвокат, засыпайте."
        
    prostitute_sleep:
      - file: "prostitute_sleep.mp3"
        text: "Проститутка, засыпай."
        
    maniac_sleep:
      - file: "maniac_sleep.mp3"
        text: "Маньяк, засыпай."
        
    doctor_sleep:
      - file: "doctor_sleep.mp3"
        text: "Доктор, засыпай."
        
    commissar_sleep:
      - file: "commissar_sleep.mp3"
        text: "Комиссар, засыпай."
        
    commissar_sergeant_sleep:
      - file: "commissar_sergeant_sleep.mp3"
        text: "Полиция, засыпайте."
        
    sergeant_sleep:
      - file: "sergeant_sleep.mp3"
        text: "Сержант, засыпай."

    lawyer_sleep:
      - file: "lawyer_sleep.mp3"
        text: "Адвокат, засыпай."
        
    poisoner_sleep:
      - file: "poisoner_sleep.mp3"
        text: "Отравитель, засыпай."

    day_start:
      - file: "day_start.mp3"
        text: "Наступило утро. Город просыпается. Посмотрим, что произошло этой ночью."
        
    discussion_start:
      - file: "discussion_start.mp3"
        text: "Начинается обсуждение."
        
    voting_start:
      - file: "voting_start.mp3"
        text: "Пришло время голосовать. Выберите подозреваемого."
        
    defense_start:
      - file: "defense_start.mp3"
        text: "У вас есть одна минута для последнего слова."
        
    verdict_start:
      - file: "verdict_start.mp3"
        text: "Жители, сделайте свой выбор. Помиловать или Казнить?"

    mafia_action:
      - file: "mafia_action.mp3"
        text: "Мафия, выберите свою цель."
        
    don_action:
      - file: "don_action.mp3"
        text: "Дон, выберите свою цель."
        
    lawyer_action:
      - file: "lawyer_action.mp3"
        text: "Адвокат, отправляйтесь на проверку."
        
    commissar_action:
      - file: "commissar_action.mp3"
        text: "Комиссар, выберите кого проверить."
        
    sergeant_action:
      - file: "sergeant_action.mp3"
        text: "Сержант, выберите кого проверить."
        
    poisoner_action:
      - file: "poisoner_action.mp3"
        text: "Отравитель, выберите свою жертву."

    prostitute_action:
      - file: "prostitute_action.mp3"
        text: "Проститутка, выберите кого навестить."
        
    maniac_action:
      - file: "maniac_action.mp3"
        text: "Маньяк, выберите свою жертву."
        
    doctor_action:
      - file: "doctor_action.mp3"
        text: "Доктор, выберите кого лечить."

    execution:
      - file: "execution.mp3"
        text: "Приговор приведен в исполнение."
        
    game_paused:
      - file: "game_paused.mp3"
        text: "Игра приостановлена."
        
    game_resumed:
      - file: "game_resumed.mp3"
        text: "Игра возобновлена."
        
    # Night Result Announcements
    prostitute_visit:
      - file: "prostitute_visit.mp3"
        text: "Проститутка провела ночь с "
        
    maniac_kill:
      - file: "maniac_kill.mp3"
        text: "Маньяк жестоко убил"
        
    doctor_heal_success:
      - file: "doctor_heal_success.mp3"
        text: "Доктор спас от смерти"
        
    doctor_heal_fail:
      - file: "doctor_heal_fail.mp3"
        text: "Лекарства Доктора оказались напрасны."

    player_killed:
      - file: "player_killed.mp3"
        text: "Мы нашли тело"
    
    nobody_killed:
      - file: "nobody_killed.mp3"
        text: "Наступило утро. Все живы."
    
    player_executed:
      - file: "player_executed.mp3"
        text: "Город казнил"
        
    poison_death:
      - file: "poison_death.mp3"
        text: "Яд наконец подействовал. Обнаружено тело"
        
    poisoner_visit:
      - file: "poisoner_visit.mp3"
        text: "Отравитель навестил"
        
    poisoner_interaction:
      - file: "poisoner_interaction.mp3"
        text: "коснулся отравленной цели и тоже погиб!"
        
    town_win:
      - file: "town_win.mp3"
        text: "Город победил! Мир возвращается."
    
    mafia_win:
      - file: "mafia_win.mp3"
        text: "Мафия победила! Город погружается во тьму."
    
    maniac_win:
      - file: "maniac_win.mp3"
        text: "Маньяк победил! Безумие восторжествовало."
        
    poisoner_win:
      - file: "poisoner_win.mp3"
        text: "Отравитель победил! Токсин поглотил город."
        
    commissar_visit:
      - file: "commissar_visit.mp3"
        text: "Комиссар проверил"
        
    sergeant_visit:
      - file: "sergeant_visit.mp3"
        text: "Сержант проверил"
        
    lawyer_visit:
      - file: "lawyer_visit.mp3"
        text: "Адвокат проверил"
        
    don_visit:
      - file: "don_visit.mp3"
        text: "Дон проверил"
        
    vote_tie:
      - file: "vote_tie.mp3"
        text: "Город не смог договориться. Наступает ночь."

    mafia_miss:
      - file: "mafia_miss.mp3"
        text: "Мафия не смогла договориться о цели."
    
    commissar_miss:
      - file: "commissar_miss.mp3"
        text: "Комиссар никого не проверил."

    doctor_miss:
      - file: "doctor_miss.mp3"
        text: "Доктор никого не вылечил."
    
    prostitute_miss:
      - file: "prostitute_miss.mp3"
        text: "Проститутка осталась дома."
        
    maniac_miss:
      - file: "maniac_miss.mp3"
        text: "Маньяк не нашел, кого убить."
        
    poisoner_miss:
      - file: "poisoner_miss.mp3"
        text: "Отравитель не использовал свои токсины этой ночью."
        
    lawyer_miss:
      - file: "lawyer_miss.mp3"
        text: "Адвокат никого не проверил."
        
    sergeant_miss:
      - file: "sergeant_miss.mp3"
        text: "Сержант никого не проверил."

    # Player Numbers (1-20)
    player_1:
      - file: "player_1.mp3"
        text: "Игрок 1"
    player_2:
      - file: "player_2.mp3"
        text: "Игрок 2"
    player_3:
      - file: "player_3.mp3"
        text: "Игрок 3"
    player_4:
      - file: "player_4.mp3"
        text: "Игрок 4"
    player_5:
      - file: "player_5.mp3"
        text: "Игрок 5"
    player_6:
      - file: "player_6.mp3"
        text: "Игрок 6"
    player_7:
      - file: "player_7.mp3"
        text: "Игрок 7"
    player_8:
      - file: "player_8.mp3"
        text: "Игрок 8"
    player_9:
      - file: "player_9.mp3"
        text: "Игрок 9"
    player_10:
      - file: "player_10.mp3"
        text: "Игрок 10"
    player_11:
      - file: "player_11.mp3"
        text: "Игрок 11"
    player_12:
      - file: "player_12.mp3"
        text: "Игрок 12"
    player_13:
      - file: "player_13.mp3"
        text: "Игрок 13"
    player_14:
      - file: "player_14.mp3"
        text: "Игрок 14"
    player_15:
      - file: "player_15.mp3"
        text: "Игрок 15"
    player_16:
      - file: "player_16.mp3"
        text: "Игрок 16"
    player_17:
      - file: "player_17.mp3"
        text: "Игрок 17"
    player_18:
      - file: "player_18.mp3"
        text: "Игрок 18"
    player_19:
      - file: "player_19.mp3"
        text: "Игрок 19"
    player_20:
      - file: "player_20.mp3"
        text: "Игрок 20"
    
    # Timer announcements (voice)
    timer_30sec:
      - file: "timer_30sec.mp3"
        text: "Осталось 30 секунд"
    
    timer_20sec:
      - file: "timer_20sec.mp3"
        text: "Осталось 20 секунд"
    
    timer_10sec:
      - file: "timer_10sec.mp3"
        text: "Осталось 10 секунд"
    
    countdown:
      nine:
        file: "countdown_9.mp3"
        text: "9"
      eight:
        file: "countdown_8.mp3"
        text: "8"
      seven:
        file: "countdown_7.mp3"
        text: "7"
      six:
        file: "countdown_6.mp3"
        text: "6"
      five:
        file: "countdown_5.mp3"
        text: "5"
      four:
        file: "countdown_4.mp3"
        text: "4"
      three:
        file: "countdown_3.mp3"
        text: "3"
      two:
        file: "countdown_2.mp3"
        text: "2"
      one:
        file: "countdown_1.mp3"
        text: "1"
  
  # Background music
  background:
    lobby:
      - file: "bg_lobby.mp3"
        loop: true
    
    night:
      - file: "bg_night.mp3"
        loop: true
    
    inactive:
      - file: "bg_waiting.mp3"
        loop: true

# Audio ducking settings
audio_mixing:
  background_volume: 0.3  # 30% when no announcements
  ducking_volume: 0.1     # 10% during announcements
  fade_duration: 500      # ms
