meta:
  id: "default"
  name: "Default Theme"
  author: "System"
  version: "1.0"
  locale: "en"

# Role name overrides for UI
roles:
  mafia: 
    display_name: "Mafia"
  doctor:
    display_name: "Doctor"
  prostitute:
    display_name: "Prostitute"
  commissar:
    display_name: "Commissar"
  maniac:
    display_name: "Maniac"
  sergeant:
    display_name: "Sergeant"
  lawyer:
    display_name: "Lawyer"
  poisoner:
    display_name: "Poisoner"
  civilian:
    display_name: "Civilian"

# Audio events (List of variants for randomization)
audio:
  events:
    role_name_mafia:
      - file: "role_mafia.mp3"
        text: "Mafia"
    role_name_doctor:
      - file: "role_doctor.mp3"
        text: "Doctor"
    role_name_prostitute:
      - file: "role_prostitute.mp3"
        text: "Prostitute"
    role_name_commissar:
      - file: "role_commissar.mp3"
        text: "Commissar"
    role_name_maniac:
      - file: "role_maniac.mp3"
        text: "Maniac"
    role_name_sergeant:
      - file: "role_sergeant.mp3"
        text: "Sergeant"
    role_name_lawyer:
      - file: "role_lawyer.mp3"
        text: "Lawyer"
    role_name_poisoner:
      - file: "role_poisoner.mp3"
        text: "Poisoner"
    role_name_civilian:
      - file: "role_civilian.mp3"
        text: "Civilian"
    game_start:
      - file: "game_start.mp3"
        text: "The game begins. Good luck to everyone."
    
    role_reveal:
      - file: "role_reveal.mp3"
        text: "The roles have been assigned. Look at your devices."
    
    night_start:
      - file: "night_start.mp3"
        text: "Night falls. The city goes to sleep."
    
    mafia_wake:
      - file: "mafia_wake.mp3"
        text: "Mafia, wake up."
    
    mafia_lawyer_wake:
      - file: "mafia_lawyer_wake.mp3"
        text: "Mafia and Lawyer, wake up."
    
    mafia_meet:
      - file: "mafia_meet.mp3"
        text: "Mafia, wake up. I see you. Get to know each other."
        
    mafia_lawyer_meet:
      - file: "mafia_lawyer_meet.mp3"
        text: "Mafia and Lawyer, wake up. I see you. Get to know each other."
    
    prostitute_wake:
      - file: "prostitute_wake.mp3"
        text: "Prostitute, wake up."
        
    maniac_wake:
      - file: "maniac_wake.mp3"
        text: "Maniac, wake up. Choose who to kill."

    doctor_wake:
      - file: "doctor_wake.mp3"
        text: "Doctor, wake up."

    commissar_wake:
      - file: "commissar_wake.mp3"
        text: "Commissar, wake up."
        
    commissar_sergeant_wake:
      - file: "commissar_sergeant_wake.mp3"
        text: "Police, wake up. Commissar and Sergeant, I am waiting for you."
        
    sergeant_wake:
      - file: "sergeant_wake.mp3"
        text: "Sergeant, wake up."
    
    lawyer_wake:
      - file: "lawyer_wake.mp3"
        text: "Lawyer, wake up."
        
    poisoner_wake:
      - file: "poisoner_wake.mp3"
        text: "Poisoner, wake up."
    
    mafia_sleep:
      - file: "mafia_sleep.mp3"
        text: "Mafia, go to sleep."
        
    mafia_lawyer_sleep:
      - file: "mafia_lawyer_sleep.mp3"
        text: "Mafia and Lawyer, go to sleep."
        
    prostitute_sleep:
      - file: "prostitute_sleep.mp3"
        text: "Prostitute, go to sleep."
        
    maniac_sleep:
      - file: "maniac_sleep.mp3"
        text: "Maniac, go to sleep."
        
    doctor_sleep:
      - file: "doctor_sleep.mp3"
        text: "Doctor, go to sleep."
        
    commissar_sleep:
      - file: "commissar_sleep.mp3"
        text: "Commissar, go to sleep."
        
    commissar_sergeant_sleep:
      - file: "commissar_sergeant_sleep.mp3"
        text: "Police, go to sleep."
        
    sergeant_sleep:
      - file: "sergeant_sleep.mp3"
        text: "Sergeant, go to sleep."

    lawyer_sleep:
      - file: "lawyer_sleep.mp3"
        text: "Lawyer, go to sleep."
        
    poisoner_sleep:
      - file: "poisoner_sleep.mp3"
        text: "Poisoner, go to sleep."

    day_start:
      - file: "day_start.mp3"
        text: "Morning has come. The city wakes up. Let's see what happened tonight."
        
    discussion_start:
      - file: "discussion_start.mp3"
        text: "The discussion begins."
        
    voting_start:
      - file: "voting_start.mp3"
        text: "It is time to vote. Choose your suspect."
        
    defense_start:
      - file: "defense_start.mp3"
        text: "You have one minute for your final speech."
        
    verdict_start:
      - file: "verdict_start.mp3"
        text: "Citizens, make your choice. Pardon or Execute?"

    mafia_action:
      - file: "mafia_action.mp3"
        text: "Mafia, choose your target."
        
    don_action:
      - file: "don_action.mp3"
        text: "Don, choose your target."
        
    lawyer_action:
      - file: "lawyer_action.mp3"
        text: "Lawyer, go for investigation."
        
    commissar_action:
      - file: "commissar_action.mp3"
        text: "Commissar, choose who to check."
        
    sergeant_action:
      - file: "sergeant_action.mp3"
        text: "Sergeant, choose who to check."
        
    poisoner_action:
      - file: "poisoner_action.mp3"
        text: "Poisoner, choose your victim."

    prostitute_action:
      - file: "prostitute_action.mp3"
        text: "Prostitute, choose who to visit."
        
    maniac_action:
      - file: "maniac_action.mp3"
        text: "Maniac, choose your victim."
        
    doctor_action:
      - file: "doctor_action.mp3"
        text: "Doctor, choose who to heal."

    execution:
      - file: "execution.mp3"
        text: "The verdict has been carried out."
        
    game_paused:
      - file: "game_paused.mp3"
        text: "Game paused."
        
    game_resumed:
      - file: "game_resumed.mp3"
        text: "Game resumed."
        
    # Night Result Announcements
    prostitute_visit:
      - file: "prostitute_visit.mp3"
        text: "The Prostitute slept with "
        
    maniac_kill:
      - file: "maniac_kill.mp3"
        text: "The Maniac brutally killed"
        
    doctor_heal_success:
      - file: "doctor_heal_success.mp3"
        text: "The Doctor saved from death"
        
    doctor_heal_fail:
      - file: "doctor_heal_fail.mp3"
        text: "The Doctor used their medicine in vain."

    player_killed:
      - file: "player_killed.mp3"
        text: "We found the body of"
    
    nobody_killed:
      - file: "nobody_killed.mp3"
        text: "Morning begins. Everyone is alive."
    
    player_executed:
      - file: "player_executed.mp3"
        text: "The town has executed"
        
    poison_death:
      - file: "poison_death.mp3"
        text: "The poison finally took effect. We found the body of"
        
    poisoner_visit:
      - file: "poisoner_visit.mp3"
        text: "The Poisoner visited"
        
    poisoner_interaction:
      - file: "poisoner_interaction.mp3"
        text: "touched the poisoned target and also died!"
        
    town_win:
      - file: "town_win.mp3"
        text: "Town Wins! Peace returns."
    
    mafia_win:
      - file: "mafia_win.mp3"
        text: "Mafia Wins! The city falls into darkness."
    
    maniac_win:
      - file: "maniac_win.mp3"
        text: "Maniac Wins! Madness prevails."
        
    poisoner_win:
      - file: "poisoner_win.mp3"
        text: "Poisoner Wins! The toxin has consumed the city."
        
    commissar_visit:
      - file: "commissar_visit.mp3"
        text: "The Commissar investigated"
        
    sergeant_visit:
      - file: "sergeant_visit.mp3"
        text: "The Sergeant investigated"
        
    lawyer_visit:
      - file: "lawyer_visit.mp3"
        text: "The Lawyer investigated"
        
    don_visit:
      - file: "don_visit.mp3"
        text: "The Don investigated"
        
    vote_tie:
      - file: "vote_tie.mp3"
        text: "The town could not agree. Night falls."

    mafia_miss:
      - file: "mafia_miss.mp3"
        text: "The Mafia could not agree on a target."
    
    commissar_miss:
      - file: "commissar_miss.mp3"
        text: "The Commissar failed to investigate anyone."

    doctor_miss:
      - file: "doctor_miss.mp3"
        text: "The Doctor did not heal anyone."
    
    prostitute_miss:
      - file: "prostitute_miss.mp3"
        text: "The Prostitute stayed home."
        
    maniac_miss:
      - file: "maniac_miss.mp3"
        text: "The Maniac didn't find anyone to kill."
        
    poisoner_miss:
      - file: "poisoner_miss.mp3"
        text: "The Poisoner didn't use their toxins tonight."
        
    lawyer_miss:
      - file: "lawyer_miss.mp3"
        text: "The Lawyer did not investigate anyone."
        
    sergeant_miss:
      - file: "sergeant_miss.mp3"
        text: "The Sergeant failed to investigate anyone."

    # Player Numbers (1-20)
    player_1:
      - file: "player_1.mp3"
        text: "Player 1"
    player_2:
      - file: "player_2.mp3"
        text: "Player 2"
    player_3:
      - file: "player_3.mp3"
        text: "Player 3"
    player_4:
      - file: "player_4.mp3"
        text: "Player 4"
    player_5:
      - file: "player_5.mp3"
        text: "Player 5"
    player_6:
      - file: "player_6.mp3"
        text: "Player 6"
    player_7:
      - file: "player_7.mp3"
        text: "Player 7"
    player_8:
      - file: "player_8.mp3"
        text: "Player 8"
    player_9:
      - file: "player_9.mp3"
        text: "Player 9"
    player_10:
      - file: "player_10.mp3"
        text: "Player 10"
    player_11:
      - file: "player_11.mp3"
        text: "Player 11"
    player_12:
      - file: "player_12.mp3"
        text: "Player 12"
    player_13:
      - file: "player_13.mp3"
        text: "Player 13"
    player_14:
      - file: "player_14.mp3"
        text: "Player 14"
    player_15:
      - file: "player_15.mp3"
        text: "Player 15"
    player_16:
      - file: "player_16.mp3"
        text: "Player 16"
    player_17:
      - file: "player_17.mp3"
        text: "Player 17"
    player_18:
      - file: "player_18.mp3"
        text: "Player 18"
    player_19:
      - file: "player_19.mp3"
        text: "Player 19"
    player_20:
      - file: "player_20.mp3"
        text: "Player 20"
    
    # Timer announcements (voice)
    timer_30sec:
      - file: "timer_30sec.mp3"
        text: "30 seconds remaining"
    
    timer_20sec:
      - file: "timer_20sec.mp3"
        text: "20 seconds remaining"
    
    timer_10sec:
      - file: "timer_10sec.mp3"
        text: "10 seconds remaining"
    
    countdown:
      nine:
        file: "countdown_9.mp3"
        text: "9"
      eight:
        file: "countdown_8.mp3"
        text: "8"
      seven:
        file: "countdown_7.mp3"
        text: "7"
      six:
        file: "countdown_6.mp3"
        text: "6"
      five:
        file: "countdown_5.mp3"
        text: "5"
      four:
        file: "countdown_4.mp3"
        text: "4"
      three:
        file: "countdown_3.mp3"
        text: "3"
      two:
        file: "countdown_2.mp3"
        text: "2"
      one:
        file: "countdown_1.mp3"
        text: "1"
  
  # Background music
  background:
    lobby:
      - file: "bg_lobby.mp3"
        loop: true
    
    night:
      - file: "bg_night.mp3"
        loop: true
    
    inactive:
      - file: "bg_waiting.mp3"
        loop: true

# Audio ducking settings
audio_mixing:
  background_volume: 0.3  # 30% when no announcements
  ducking_volume: 0.1     # 10% during announcements
  fade_duration: 500      # ms
